# Generated by Django 2.1.5 on 2019-01-21 18:07

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
                ('number_of_bags', models.SmallIntegerField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('transfer_date', models.DateField(null=True)),
                ('is_transferred', models.BooleanField(default=False)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PickUpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=32)),
                ('postal_code', models.CharField(max_length=8)),
                ('phone_number', models.CharField(max_length=16)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('comments', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustedInstitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('purpose', models.CharField(max_length=128)),
                ('localization', models.CharField(max_length=64)),
                ('target_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='pick_up_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GiveItFreeApp.PickUpAddress'),
        ),
        migrations.AddField(
            model_name='gift',
            name='trusted_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GiveItFreeApp.TrustedInstitution'),
        ),
    ]
