# Generated by Django 2.1.5 on 2019-01-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveItFreeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='trustedinstitution',
            name='needs',
            field=models.CharField(default='ads', max_length=128),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='trustedinstitution',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='trustedinstitution',
            name='target_groups',
            field=models.ManyToManyField(to='GiveItFreeApp.TargetGroup'),
        ),
    ]
