# Generated by Django 2.2.7 on 2019-11-27 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GiveItFreeApp', '0002_auto_20190124_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetgroup',
            options={'verbose_name': 'Grupę docelową', 'verbose_name_plural': 'Grupy docelowe'},
        ),
        migrations.AlterModelOptions(
            name='trustedinstitution',
            options={'verbose_name': 'Zaufaną instytucję', 'verbose_name_plural': 'Zaufane instytucje'},
        ),
        migrations.AlterField(
            model_name='targetgroup',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Nazwa grupy'),
        ),
        migrations.AlterField(
            model_name='trustedinstitution',
            name='localization',
            field=models.CharField(max_length=64, verbose_name='Lokalizacja'),
        ),
        migrations.AlterField(
            model_name='trustedinstitution',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa instytucji'),
        ),
        migrations.AlterField(
            model_name='trustedinstitution',
            name='needs',
            field=models.CharField(max_length=128, verbose_name='Potrzebne datki'),
        ),
        migrations.AlterField(
            model_name='trustedinstitution',
            name='purpose',
            field=models.CharField(max_length=128, verbose_name='Cel i misja'),
        ),
        migrations.AlterField(
            model_name='trustedinstitution',
            name='target_groups',
            field=models.ManyToManyField(to='GiveItFreeApp.TargetGroup', verbose_name='Grupy docelowe'),
        ),
        migrations.CreateModel(
            name='CharityCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
                ('purpose', models.CharField(max_length=128, verbose_name='Cel zbiórki')),
                ('items_needed', models.CharField(max_length=128, verbose_name='Co jest potrzebne')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
