# Generated by Django 2.2.7 on 2019-11-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveItFreeApp', '0003_auto_20191127_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycollection',
            name='address',
            field=models.CharField(default='n/d', max_length=256, verbose_name='Pełen adres'),
            preserve_default=False,
        ),
    ]
