# Generated by Django 2.2.7 on 2019-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GiveItFreeApp', '0005_auto_20191203_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycollection',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default='1999-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='charitycollection',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
    ]
