# Generated by Django 2.2.7 on 2019-12-04 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GiveItFreeApp', '0006_auto_20191204_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charitycollection',
            options={'verbose_name': 'Zbiórka charytatywna', 'verbose_name_plural': 'Zbiórki charytatywne'},
        ),
    ]
